// Package demo prepares a self-contained demo: three sample apps, their event
// catalogs and 90 days of generated data, so the dashboard can be explored locally.
package demo

import (
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/RedHiwiK/HiwiKInsight/internal/auth"
	"github.com/RedHiwiK/HiwiKInsight/internal/config"
	"github.com/RedHiwiK/HiwiKInsight/internal/store"
	"github.com/RedHiwiK/HiwiKInsight/internal/tz"
)

//go:embed catalogs/*.yaml
var catalogs embed.FS

const (
	// Days of generated SDK events, ending today.
	Days = 90
	// Seed makes every demo database identical apart from the dates.
	Seed = 2026

	timezone   = "America/Los_Angeles"
	queryToken = "demo-token"
)

// Prepare creates (or reuses) a demo data directory and returns its config.
//
// The directory gets config.yaml (user demo / password demo, query token demo-token),
// catalogs/*.yaml and, on the first run, a database with generated data. Later runs
// keep the database; delete the directory to start over with fresh dates.
func Prepare(dir, listen string) (*config.Config, error) {
	if err := os.MkdirAll(filepath.Join(dir, "catalogs"), 0o750); err != nil {
		return nil, err
	}
	for _, a := range apps {
		b, err := catalogs.ReadFile("catalogs/" + a.key + ".yaml")
		if err != nil {
			return nil, err
		}
		if err := os.WriteFile(filepath.Join(dir, "catalogs", a.key+".yaml"), b, 0o640); err != nil {
			return nil, err
		}
	}
	hash, err := auth.HashPassword("demo")
	if err != nil {
		return nil, err
	}
	path := filepath.Join(dir, "config.yaml")
	if err := os.WriteFile(path, []byte(configYAML(listen, hash)), 0o640); err != nil {
		return nil, err
	}
	cfg, err := config.Load(path)
	if err != nil {
		return nil, err
	}
	if err := tz.Set(cfg.Timezone); err != nil {
		return nil, err
	}

	db := cfg.DBPath()
	if _, err := os.Stat(db); err == nil {
		slog.Info("demo: reusing existing database; delete the data directory to regenerate", "path", db)
		return cfg, nil
	} else if !errors.Is(err, fs.ErrNotExist) {
		return nil, err
	}
	// Generate into a temporary file so an interrupted run never leaves a half-filled database behind.
	tmp := db + ".partial"
	for _, p := range []string{tmp, tmp + "-wal", tmp + "-shm"} {
		os.Remove(p)
	}
	slog.Info("demo: generating data", "apps", len(apps), "days", Days)
	began := time.Now()
	st, err := store.Open(tmp)
	if err != nil {
		return nil, err
	}
	sum, err := Generate(st, time.Now())
	if cerr := st.Close(); err == nil {
		err = cerr
	}
	if err != nil {
		return nil, fmt.Errorf("demo: generate: %w", err)
	}
	if err := os.Rename(tmp, db); err != nil {
		return nil, err
	}
	slog.Info("demo: data ready", "installs", sum.Installs, "events", sum.Events, "notifications", sum.Notifications,
		"sales_rows", sum.SalesRows, "took", time.Since(began).Round(time.Millisecond).String())
	return cfg, nil
}

// configYAML is the demo deployment: no mail, no App Store Connect, reports and alerts off.
func configYAML(listen, hash string) string {
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by "hiwikinsight demo" and rewritten on every demo run.
# See examples/config.example.yaml for a fully documented configuration.
listen: %q
data_dir: .
timezone: %s
language: en
currency: USD

apps:
`, listen, timezone)
	for _, a := range apps {
		fmt.Fprintf(&b, "  - key: %s\n    bundle_id: %s\n    name: %s\n    color: %s\n    catalog: catalogs/%s.yaml\n    products:\n",
			a.key, a.bundle, a.name, a.color, a.key)
		for _, p := range a.products {
			fmt.Fprintf(&b, "      %s: %q\n", p.id, p.name)
		}
		b.WriteString("    paywall_contexts:\n")
		ctxs := append([]paywallContext(nil), a.contexts...)
		sort.Slice(ctxs, func(i, j int) bool { return ctxs[i].key < ctxs[j].key })
		for _, c := range ctxs {
			fmt.Fprintf(&b, "      %s: %q\n", c.key, c.label)
		}
	}
	fmt.Fprintf(&b, `
dashboard:
  users:
    - username: demo
      password_hash: '%s' # bcrypt of "demo"

query:
  tokens: [%s]

reports:
  daily: false
  weekly: false

alerts:
  enabled: false
`, hash, queryToken)
	return b.String()
}
